### ISSUE TITLE
FASTAFileParserFactory.getInstance() method is not static

### ISSUE THREAD

**Issue by MrCreosote** [yeastrc/java-fasta-utils#1]
I feel like I'm missing something here, but in the README:
```java
FASTAFileParserFactory.getInstance().getFASTAFileParser(  new File( filename ) ) )
```

[getInstance()](https://github.com/yeastrc/java-fasta-utils/blob/master/src/main/org/yeastrc/proteomics/fasta/FASTAFileParserFactory.java#L26) is an instance method, not a static method, and so can't be called unless you already have an instance, which you can only get via calling `getInstance()`.

The workaround is to C&P the contents of `FASTAFileParserFactory.getFASTAFileParser()` and use that instead.

**Comment by mriffle** [comment]
Ooof, no, you're not missing anything--that's just an embarrassing bug! I never caught that since I don't instantiate my objects this way. Thank you so much for reporting it! I've updated the project with the fix.

**Comment by MrCreosote** [comment]
Out of curiosity, how do you instantiate your objects?

One other minor thing I've noticed is that [close()](https://github.com/yeastrc/java-fasta-utils/blob/master/src/main/org/yeastrc/proteomics/fasta/FASTAFileParser.java#L143) throws `Exception` instead of `IOException` which means an unnecessary catch & cast block. I can make a new ticket for this if you wish.

**Comment by mriffle** [comment]
I previously instantiated directly like you proposed as a fix, but I think I'll start using this convenience class for that going forward.

I updated close() to throw IOException instead.

**Comment by MrCreosote** [comment]
Great, thanks for the fixes.
